version: '3.8'

services:
  bookingclone.api:
    image: ${DOCKER_REGISTRY-}bookingcloneapi
    build:
      context: .
      dockerfile: src/Services/BookingClone.API/Dockerfile

  bookingclone.yarp:
    image: ${DOCKER_REGISTRY-}bookingcloneyarp
    build:
      context: .
      dockerfile: src/Proxy/BookingClone.YARP/Dockerfile

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9



